//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int id { get; set; }
        public string region { get; set; }
        public string district { get; set; }
        public string city { get; set; }
        public string indexx { get; set; }
        public string street { get; set; }
        public string houses { get; set; }
    }
}
